name: Kernel Builder

on:
  workflow_dispatch:
    inputs:
         BRANCH_NAME:
          description: "Kernel Tree Branch Name"
          required: true
          default: "sapphire-staging"

env:
  BRANCH_NAME: ${{ github.event.inputs.BRANCH_NAME }}
  BUILD_ID: ${{ github.run_number }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Initializing build environment
        run: |
          sudo apt-get update -y
          sudo apt-get install automake bc bison build-essential ccache clang cpio curl gcc git libc6 lld llvm libncurses5-dev libssl-dev libstdc++6 make python3-pip unzip wget zip zipalign -y

      - name: Building
        run: |
          bash build.sh

      - name: Upload
        run: |
            cd Anykernel
            ZIP=$(echo *.zip)
            echo $ZIP
            if [ -e $ZIP ]; then
                curl -F chat_id="$TG_CHAT_ID" \
                -F document=@"./IMMENSiTY.zip" \
                -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKEN/sendDocument \
                -F caption="$@TeraaBytee"
            else
                curl -F chat_id="$CHAT_ID" \
                -F document=@"out/error.log" \
                -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKEN/sendDocument \
                -F caption="@TeraaBytee"
            fi
