name: Kernel Builder

on:
  workflow_dispatch:
    inputs:
         BRANCH_NAME:
          description: "Kernel Tree Branch Name"
          required: true
          default: "sapphire-staging"

env:
  BRANCH_NAME: ${{ github.event.inputs.BRANCH_NAME }}
  BUILD_ID: ${{ github.run_number }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sushrut1101/docker:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Building
        run: |
          bash build.sh

      - name: Upload
        run: |
            cd Anykernel
            ZIP=$(echo *.zip)
            if [ -e $ZIP ]; then
                curl -F document=@"$ZIP" https://api.telegram.org/bot$BOT_TOKEN/sendDocument?chat_id=$TG_CHAT_ID
            else
                curl -F chat_id="$CHAT_ID" \
                -F document=@"out/error.log" \
                -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKEN/sendDocument \
                -F caption="@TeraaBytee"
            fi
