name: Kernel Builder

on:
  workflow_dispatch:
    inputs:
         BRANCH_NAME:
          description: "Kernel Tree Branch Name"
          required: true
          default: "LA.UM.9.1.r1-11700"

env:
  BRANCH_NAME: ${{ github.event.inputs.BRANCH_NAME }}
  BUILD_ID: ${{ github.run_number }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
  SGIT_NAME: ${{ secrets.SGIT_NAME }}
  SGIT_TOKEN: ${{ secrets.SGIT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Initializing build environment
        run: |
          sudo apt-get install -y --no-install-recommends automake bc bison build-essential ccache clang cpio curl device-tree-compiler gcc git libc6 lld llvm libncurses5-dev libssl-dev libstdc++6 make python2 python3-pip unzip wget zip zipalign
     
      - name: Building
        run: |
          bash build.sh
